apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: retasc-konflux-test
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-lholecek-tenant/retasc-konflux-test/retasc-konflux-test@sha256:8d8cb258021a7ffb701d1519fd757915891b25d21e1cd6a4644bdfafb8ff65ed
        name: my-go
        resources: {}
status: {}
