apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: retasc-konflux-test
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-lholecek-tenant/retasc-konflux-test/retasc-konflux-test@sha256:4164d25ed63008e8ccf41ba3833343f3aafe8ec61cb2ad9a222260c6aa874942
        name: my-go
        resources: {}
status: {}
