apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: retasc-konflux-test
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-lholecek-tenant/retasc-konflux-test/retasc-konflux-test@sha256:d09cec8bede8c30fdc1f7eb39741bc590d3a78d18441660f3f81647deff8b207
        name: my-go
        resources: {}
status: {}
