apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retasc-konflux-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retasc-konflux-test
    app.kubernetes.io/part-of: retasc-konflux-test
  name: retasc-konflux-test
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: retasc-konflux-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: retasc-konflux-test
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-lholecek-tenant/retasc-konflux-test/retasc-konflux-test@sha256:ccf7816081b3065a2f36ba6778dbbdf21c63df7531d33728283b502bb0730a65
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
