apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retasc-konflux-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retasc-konflux-test
    app.kubernetes.io/part-of: retasc-konflux-test
  name: retasc-konflux-test
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: retasc-konflux-test
status:
  loadBalancer: {}
